"""
MkDocs Navigation Updater

Automatically updates mkdocs.yml with generated documentation files,
intelligently merging with existing navigation structure.
"""

import os
import re
import logging
import yaml
from pathlib import Path
from typing import Dict, List, Any, Optional, Set
from collections import OrderedDict


logger = logging.getLogger('mkdocs.plugins.llm-autodoc.nav-updater')


class NavUpdater:
    """
    Updates mkdocs.yml navigation with generated documentation.

    Features:
    - Intelligent merging with existing nav structure
    - Preserves manual entries
    - Organizes generated docs by category
    - Handles incremental updates
    """

    # Marker to identify auto-generated sections
    GENERATED_MARKER = "# AUTO-GENERATED BY LLM-AUTODOC"
    GENERATED_START = "# BEGIN AUTO-GENERATED"
    GENERATED_END = "# END AUTO-GENERATED"

    def __init__(self, mkdocs_yml_path: str, docs_dir: str):
        self.mkdocs_yml_path = Path(mkdocs_yml_path)
        self.docs_dir = Path(docs_dir)
        self.config = None
        self.nav = None

    def load_config(self) -> bool:
        """Load mkdocs.yml configuration"""
        try:
            if not self.mkdocs_yml_path.exists():
                logger.error(f"mkdocs.yml not found at: {self.mkdocs_yml_path}")
                return False

            with open(self.mkdocs_yml_path, 'r', encoding='utf-8') as f:
                self.config = yaml.safe_load(f)

            self.nav = self.config.get('nav', [])
            logger.info(f"Loaded mkdocs.yml from {self.mkdocs_yml_path}")
            return True

        except Exception as e:
            logger.error(f"Error loading mkdocs.yml: {e}")
            return False

    def update_navigation(
        self,
        generated_files: List[str],
        categories: Optional[Dict[str, List[str]]] = None
    ) -> bool:
        """
        Update navigation with generated files.

        Args:
            generated_files: List of generated markdown file paths
            categories: Optional categorization of files

        Returns:
            True if update successful
        """
        if not self.load_config():
            return False

        logger.info(f"Updating navigation with {len(generated_files)} generated files...")

        # Organize files by category
        if not categories:
            categories = self._auto_categorize_files(generated_files)

        # Build new nav structure for generated docs
        generated_nav = self._build_generated_nav(categories)

        # Merge with existing nav
        merged_nav = self._merge_navigation(self.nav, generated_nav)

        # Update config
        self.config['nav'] = merged_nav

        # Save back to file
        return self._save_config()

    def _auto_categorize_files(self, files: List[str]) -> Dict[str, List[str]]:
        """
        Automatically categorize files based on their paths.

        Returns:
            Dictionary: category -> list of files
        """
        categories = {
            'Overview': [],
            'Architecture': [],
            'Modules': [],
            'API Reference': [],
            'Other': []
        }

        for file_path in files:
            rel_path = self._get_relative_path(file_path)

            if '/overview/' in file_path:
                categories['Overview'].append(rel_path)
            elif '/modules/' in file_path:
                categories['Modules'].append(rel_path)
            elif '/api/' in file_path or '/classes/' in file_path:
                categories['API Reference'].append(rel_path)
            elif 'architecture' in file_path.lower():
                categories['Architecture'].append(rel_path)
            else:
                categories['Other'].append(rel_path)

        # Remove empty categories
        categories = {k: v for k, v in categories.items() if v}

        # Sort files within each category
        for category in categories:
            categories[category].sort()

        logger.info(f"Auto-categorized files into {len(categories)} categories")
        return categories

    def _get_relative_path(self, file_path: str) -> str:
        """Get path relative to docs_dir"""
        try:
            path = Path(file_path)
            rel = path.relative_to(self.docs_dir)
            return str(rel)
        except ValueError:
            # If not relative to docs_dir, return as-is
            return file_path

    def _build_generated_nav(self, categories: Dict[str, List[str]]) -> List[Any]:
        """
        Build navigation structure for generated documentation.

        Returns:
            List of nav items suitable for mkdocs.yml
        """
        nav_items = []

        # Add a top-level "Generated Documentation" section
        generated_section = {
            'Generated Documentation': []
        }

        for category, files in categories.items():
            if not files:
                continue

            # Create category subsection
            category_items = []

            for file_path in files:
                # Get nice title from file
                title = self._get_title_from_file(file_path)
                category_items.append({title: file_path})

            # Add category to generated section
            generated_section['Generated Documentation'].append({
                category: category_items
            })

        nav_items.append(generated_section)
        return nav_items

    def _get_title_from_file(self, file_path: str) -> str:
        """Extract title from markdown file or generate from filename"""
        full_path = self.docs_dir / file_path

        try:
            if full_path.exists():
                with open(full_path, 'r', encoding='utf-8') as f:
                    content = f.read(500)  # Read first 500 chars

                # Look for first # heading
                match = re.search(r'^#\s+(.+)$', content, re.MULTILINE)
                if match:
                    return match.group(1).strip()

        except Exception as e:
            logger.debug(f"Could not extract title from {file_path}: {e}")

        # Fallback: generate from filename
        name = Path(file_path).stem
        # Convert from kebab-case or snake_case to Title Case
        title = name.replace('-', ' ').replace('_', ' ').title()
        # Remove number prefixes like "00-"
        title = re.sub(r'^\d+-', '', title)
        return title

    def _merge_navigation(self, existing_nav: List, generated_nav: List) -> List:
        """
        Merge generated nav with existing nav.

        Strategy:
        1. Keep all existing manual entries
        2. Remove old auto-generated sections
        3. Add new auto-generated sections
        4. Preserve order where possible
        """
        merged = []

        # Track if we found existing generated section
        found_generated = False

        for item in existing_nav:
            # Check if this is a generated documentation section
            if self._is_generated_section(item):
                found_generated = True
                # Skip it - we'll add the new one
                logger.info("Removing old auto-generated section")
                continue

            # Keep manual entries
            merged.append(item)

        # Add new generated section
        if generated_nav:
            logger.info("Adding new auto-generated navigation section")
            merged.extend(generated_nav)

        if not found_generated and generated_nav:
            logger.info("This is the first time auto-generated nav is being added")

        return merged

    def _is_generated_section(self, nav_item: Any) -> bool:
        """Check if a nav item is auto-generated"""
        if isinstance(nav_item, dict):
            # Check if it has the 'Generated Documentation' key
            if 'Generated Documentation' in nav_item:
                return True

            # Check for marker comments (stored as special keys)
            for key in nav_item.keys():
                if isinstance(key, str) and 'generated' in key.lower():
                    return True

        return False

    def _save_config(self) -> bool:
        """Save updated configuration back to mkdocs.yml"""
        try:
            # Create backup
            backup_path = self.mkdocs_yml_path.with_suffix('.yml.backup')
            with open(self.mkdocs_yml_path, 'r') as f:
                backup_content = f.read()
            with open(backup_path, 'w') as f:
                f.write(backup_content)

            logger.info(f"Created backup: {backup_path}")

            # Save updated config
            with open(self.mkdocs_yml_path, 'w', encoding='utf-8') as f:
                # Add header comment
                f.write("# This file is automatically updated by mkdocs-llm-autodoc plugin\n")
                f.write("# Manual changes are preserved, but 'Generated Documentation' section is auto-managed\n\n")

                yaml.dump(
                    self.config,
                    f,
                    default_flow_style=False,
                    allow_unicode=True,
                    sort_keys=False
                )

            logger.info(f"✅ Updated mkdocs.yml successfully")
            return True

        except Exception as e:
            logger.error(f"Error saving mkdocs.yml: {e}")
            return False

    def get_current_nav_structure(self) -> Dict[str, Any]:
        """Get current navigation structure for analysis"""
        if not self.config:
            self.load_config()

        return {
            'total_items': len(self.nav) if self.nav else 0,
            'has_generated_section': any(self._is_generated_section(item) for item in self.nav) if self.nav else False,
            'manual_sections': self._count_manual_sections(),
        }

    def _count_manual_sections(self) -> int:
        """Count non-generated sections"""
        if not self.nav:
            return 0

        count = 0
        for item in self.nav:
            if not self._is_generated_section(item):
                count += 1

        return count

    def remove_generated_sections(self) -> bool:
        """Remove all auto-generated sections from navigation"""
        if not self.load_config():
            return False

        original_count = len(self.nav)

        # Filter out generated sections
        self.nav = [item for item in self.nav if not self._is_generated_section(item)]

        removed_count = original_count - len(self.nav)

        if removed_count > 0:
            self.config['nav'] = self.nav
            logger.info(f"Removed {removed_count} auto-generated sections")
            return self._save_config()

        logger.info("No auto-generated sections found to remove")
        return True

    def preview_changes(self, generated_files: List[str]) -> str:
        """
        Preview what changes would be made without applying them.

        Returns:
            String description of changes
        """
        if not self.load_config():
            return "Error: Could not load mkdocs.yml"

        categories = self._auto_categorize_files(generated_files)
        generated_nav = self._build_generated_nav(categories)
        merged_nav = self._merge_navigation(self.nav, generated_nav)

        preview = []
        preview.append("=" * 60)
        preview.append("NAVIGATION UPDATE PREVIEW")
        preview.append("=" * 60)

        # Current state
        preview.append(f"\nCurrent navigation: {len(self.nav)} items")
        preview.append(f"  - Manual sections: {self._count_manual_sections()}")
        preview.append(f"  - Generated sections: {'Yes' if any(self._is_generated_section(item) for item in self.nav) else 'No'}")

        # New state
        preview.append(f"\nNew navigation: {len(merged_nav)} items")
        preview.append(f"  - Files to add: {len(generated_files)}")
        preview.append(f"  - Categories: {', '.join(categories.keys())}")

        # What will change
        preview.append("\nChanges:")
        has_existing = any(self._is_generated_section(item) for item in self.nav)

        if has_existing:
            preview.append("  - Replace existing 'Generated Documentation' section")
        else:
            preview.append("  - Add new 'Generated Documentation' section")

        preview.append("  - Preserve all manual navigation entries")

        preview.append("\nNew structure:")
        for category, files in categories.items():
            preview.append(f"  - {category}: {len(files)} files")

        preview.append("=" * 60)

        return '\n'.join(preview)


class SmartNavBuilder:
    """
    Builds intelligent navigation structures based on file content and relationships.
    """

    def __init__(self, docs_dir: str):
        self.docs_dir = Path(docs_dir)

    def build_hierarchical_nav(self, files: List[str]) -> List[Dict]:
        """
        Build hierarchical navigation based on file structure and priorities.

        Args:
            files: List of generated file paths

        Returns:
            Hierarchical navigation structure
        """
        # Group by directory
        by_directory = self._group_by_directory(files)

        # Build hierarchy
        nav = []

        # Special handling for overview files
        if 'overview' in by_directory:
            nav.append(self._build_overview_section(by_directory['overview']))

        # Handle module documentation
        if 'modules' in by_directory:
            nav.append(self._build_modules_section(by_directory['modules']))

        # Handle API documentation
        if 'api' in by_directory:
            nav.append(self._build_api_section(by_directory['api']))

        # Handle any remaining directories
        for dir_name, dir_files in by_directory.items():
            if dir_name not in ['overview', 'modules', 'api']:
                nav.append(self._build_generic_section(dir_name, dir_files))

        return nav

    def _group_by_directory(self, files: List[str]) -> Dict[str, List[str]]:
        """Group files by their parent directory"""
        groups = {}

        for file_path in files:
            path = Path(file_path)
            # Get first directory after docs_dir
            try:
                rel_path = path.relative_to(self.docs_dir)
                parts = rel_path.parts

                if len(parts) > 1:
                    dir_name = parts[0]
                else:
                    dir_name = 'root'

                if dir_name not in groups:
                    groups[dir_name] = []

                groups[dir_name].append(str(rel_path))

            except ValueError:
                # Not relative to docs_dir
                continue

        return groups

    def _build_overview_section(self, files: List[str]) -> Dict:
        """Build overview section with proper ordering"""
        # Sort overview files by priority
        priority_order = [
            'overview-index',
            '00-overview',
            'project-overview',
            'getting-started',
            'architecture',
        ]

        def sort_key(file_path: str):
            name = Path(file_path).stem.lower()
            for i, priority in enumerate(priority_order):
                if priority in name:
                    return i
            return len(priority_order)

        sorted_files = sorted(files, key=sort_key)

        items = []
        for file_path in sorted_files:
            title = self._get_nice_title(file_path)
            items.append({title: file_path})

        return {'Overview': items}

    def _build_modules_section(self, files: List[str]) -> Dict:
        """Build modules section"""
        sorted_files = sorted(files)

        items = []
        for file_path in sorted_files:
            title = self._get_nice_title(file_path)
            items.append({title: file_path})

        return {'Modules': items}

    def _build_api_section(self, files: List[str]) -> Dict:
        """Build API reference section with sub-sections"""
        # Group by subsection (classes, functions, etc.)
        subsections = {}

        for file_path in files:
            parts = Path(file_path).parts
            if len(parts) > 2 and parts[1] in ['classes', 'functions']:
                subsection = parts[1].title()
                if subsection not in subsections:
                    subsections[subsection] = []
                subsections[subsection].append(file_path)
            else:
                if 'Other' not in subsections:
                    subsections['Other'] = []
                subsections['Other'].append(file_path)

        # Build structure
        items = []
        for subsection, sub_files in sorted(subsections.items()):
            sub_items = []
            for file_path in sorted(sub_files):
                title = self._get_nice_title(file_path)
                sub_items.append({title: file_path})

            items.append({subsection: sub_items})

        return {'API Reference': items}

    def _build_generic_section(self, dir_name: str, files: List[str]) -> Dict:
        """Build generic section for other directories"""
        title = dir_name.replace('-', ' ').replace('_', ' ').title()

        items = []
        for file_path in sorted(files):
            file_title = self._get_nice_title(file_path)
            items.append({file_title: file_path})

        return {title: items}

    def _get_nice_title(self, file_path: str) -> str:
        """Generate nice title from file path"""
        name = Path(file_path).stem
        # Remove number prefixes
        name = re.sub(r'^\d+-', '', name)
        # Convert to title case
        title = name.replace('-', ' ').replace('_', ' ').title()
        return title
